services:
  # Config Server
  configsvr:
    image: mongo:7.0
    container_name: mongo-config
    command: mongod --configsvr --replSet configrs --port 27019 --bind_ip_all
    ports:
      - "27019:27019"
    volumes:
      - config-data:/data/db
    networks:
      - mongo-net

  # Shard 1
  shard1:
    image: mongo:7.0
    container_name: mongo-shard1
    command: mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip_all
    ports:
      - "27021:27018"
    volumes:
      - shard1-data:/data/db
    networks:
      - mongo-net

  # Shard 2
  shard2:
    image: mongo:7.0
    container_name: mongo-shard2
    command: mongod --shardsvr --replSet shard2rs --port 27018 --bind_ip_all
    ports:
      - "27022:27018"
    volumes:
      - shard2-data:/data/db
    networks:
      - mongo-net

  # Shard 3
  shard3:
    image: mongo:7.0
    container_name: mongo-shard3
    command: mongod --shardsvr --replSet shard3rs --port 27018 --bind_ip_all
    ports:
      - "27023:27018"
    volumes:
      - shard3-data:/data/db
    networks:
      - mongo-net

  # Mongos Router
  mongos:
    image: mongo:7.0
    container_name: mongos
    command: mongos --configdb configrs/mongo-config:27019 --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    depends_on:
      - configsvr
      - shard1
      - shard2
      - shard3
    networks:
      - mongo-net
    restart: on-failure

  mongo-init:
    image: docker:27-cli
    container_name: mongo-init
    depends_on:
      - mongos
      - configsvr
      - shard1
      - shard2
      - shard3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-mongo.sh:/init-mongo.sh
      - ./mongo-init.js:/mongo-init.js
    command: sh /init-mongo.sh
    networks:
      - mongo-net
    restart: "no"

  # Consumer
  consumer:
    build: ./consumer
    container_name: mongo-consumer
    depends_on:
      - mongo-init
    networks:
      - mongo-net
      - kafka-net
    restart: on-failure

volumes:
  config-data:
  shard1-data:
  shard2-data:
  shard3-data:


networks:
  mongo-net:
    driver: bridge
  kafka-net:
    external: true
    name: kafka_kafka-net
